server:
  port: 8080

logging:
  file:
    name: D:/Projects/Codes/IMS/logs/IMS.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/morebite
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /**